remote_theme: jekyll/minima
minima:
  skin: dark
layout: home
title: Thoughts of The Day config test sentence.
author: Z. Wolfe
description: Just my Thoughts...
header_pages:
  - _pages/about.md

include:
    - _pages
